const projects = [
    {
      title: "Project One",
      tags: ["React", "Next.js", "Tailwind"],
      description: "This is a great project that I worked on...",
      achievements: "Integrate with a CMS for dynamic content.",
      takeaways: "Advanced state management in React.",
      improvements: "Used TypeScript for type safety.",
      mainImage:"/example.jpg",
      resumePoints:["","",""],
      resumeHeading:"",
      year: 2023,
      inResume:true,
      highlight:true,
      images: ["/example.jpg", "/example.jpg", "/example.jpg", "/example.jpg"],
    },
    {
        title: "Project One",
        tags: ["React", "Next.js", "Tailwind", "AI", "VR", "Personal"],
        description: "This is a great project that I worked on...",
        achievements: "Integrate with a CMS for dynamic content.",
        takeaways: "Advanced state management in React.",
        improvements: "Used TypeScript for type safety.",
        mainImage:"/example.jpg",
        resumePoints:["","",""],
        resumeHeading:"",
        year: 2023,
        inResume:true,
        highlight:true,
        images: ["/example.jpg", "/example.jpg", "/example.jpg", "/example.jpg"],
      },
      {
        title: "Project One",
        tags: ["React", "Next.js", "Tailwind"],
        description: "This is a great project that I worked on...",
        achievements: "Integrate with a CMS for dynamic content.",
        takeaways: "Advanced state management in React.",
        improvements: "Used TypeScript for type safety.",
        mainImage:"/example.jpg",
        resumePoints:["","",""],
        resumeHeading:"",
        year: 2023,
        inResume:true,
        highlight:true,
        images: ["/example.jpg", "/example.jpg", "/example.jpg", "/example.jpg"],
      },
      {
        title: "Project One",
        tags: ["React", "Next.js", "Tailwind"],
        description: "This is a great project that I worked on...",
        achievements: "Integrate with a CMS for dynamic content.",
        takeaways: "Advanced state management in React.",
        improvements: "Used TypeScript for type safety.",
        mainImage:"/example.jpg",
        resumePoints:["","",""],
        resumeHeading:"",
        year: 2023,
        inResume:true,
        highlight:true,
        images: ["/example.jpg", "/example.jpg", "/example.jpg", "/example.jpg"],
      },
      {
        title: "Project One",
        tags: [ "Python"],
        description: "This is a great project that I worked on...",
        achievements: "Integrate with a CMS for dynamic content.",
        takeaways: "Advanced state management in React.",
        improvements: "Used TypeScript for type safety.",
        mainImage:"/example.jpg",
        resumePoints:["","",""],
        resumeHeading:"",
        year: 2023,
        inResume:true,
        highlight:true,
        images: ["/example.jpg", "/example.jpg", "/example.jpg", "/example.jpg"],
      },
  ];

  export default projects;